version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.15.1
    steps:
    - checkout
    - run:
        name: update-npm
        command: sudo npm install -g npm@latest
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install-npm-wee
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: test
        command: npm test
    - run:
        name: build
        command: npm run build
    - persist_to_workspace:
        root: ~/project
        paths: .
  deploy:
    docker:
    - image: circleci/node:10.15.1
    working_directory: ~/project
    steps:
    - attach_workspace:
        at: ~/project
    - checkout
    - run:
        name: deploy to ftp
        command: npm run ftp-deploy
workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
    triggers:
    - schedule:
        cron: "0 1,7,13,18,19 * * *"
        filters:
          branches:
            only: master
